update jhipster support to 7.1.0

diff --git a/.github/workflows/react.yml b/.github/workflows/react.yml
--- a/.github/workflows/react.yml
+++ b/.github/workflows/react.yml
@@ -1,5 +1,5 @@
 #
-# Copyright 2013-2020 the original author or authors from the JHipster project.
+# Copyright 2013-2021 the original author or authors from the JHipster project.
 #
 # This file is part of the JHipster project, see https://www.jhipster.tech/
 # for more information.
@@ -8,7 +8,7 @@
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
-#      http://www.apache.org/licenses/LICENSE-2.0
+#      https://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
@@ -18,141 +18,279 @@
 #
 
 name: React
-on: [push, pull_request]
-env:
-    JHI_RUN_APP: 1
-    JHI_JDK: 11
-    JHI_LIB_REPO: https://github.com/jhipster/jhipster.git
-    JHI_LIB_BRANCH: release
-    JHI_GEN_REPO: https://github.com/jhipster/generator-jhipster.git
-    JHI_GEN_BRANCH: release
-    SPRING_OUTPUT_ANSI_ENABLED: ALWAYS
-    SPRING_JPA_SHOW_SQL: false
-    JHI_DISABLE_WEBPACK_LOGS: true
-    JHI_E2E_HEADLESS: true
-    JHI_SCRIPTS: ./test-integration/scripts
-    NG_CLI_ANALYTICS: 'false'
-    JHI_GITHUB_CI: true
+concurrency:
+  # Group PRs by head_ref, push to main branch by commit id, and others branch by ref.
+  group: ${{ github.workflow }}-${{ github.head_ref || (github.ref == 'refs/heads/main' && github.sha) || github.ref }}
+  cancel-in-progress: true
+on:
+  push:
+    branches-ignore:
+      - 'dependabot/**'
+      - 'skip_ci*'
+    paths-ignore:
+      - 'generators/*client/templates/angular/**'
+      - 'generators/*client/templates/vue/**'
+  pull_request:
+    types: [closed, opened, synchronize, reopened]
+    branches:
+      - '*'
+    paths-ignore:
+      - 'package*.json'
+      - 'generators/*client/templates/angular/**'
+      - 'generators/*client/templates/vue/**'
 jobs:
-    applications:
-        name: ${{ matrix.app-type }}
-        runs-on: ${{ matrix.os }}
-        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
-        timeout-minutes: 40
-        strategy:
-            fail-fast: false
-            matrix:
-                node_version: [12.16.1]
-                os: [ubuntu-latest]
-                app-type:
-                    - react-default
-                    - react-maven-psql-es-noi18n-mapsid
-                    - react-maven-h2mem-memcached
-                    - react-maven-cassandra-session-redis
-                    - react-maven-couchbase-caffeine
-                    - react-gradle-psql-es-noi18n-mapsid
-                    - react-gradle-h2mem-memcached
-                    - react-gradle-cassandra-session-redis
-                    - react-gradle-couchbase-caffeine
-                include:
-                    - app-type: react-default
-                      entity: sql
-                      profile: prod
-                      war: 0
-                      protractor: 1
-                    - app-type: react-maven-psql-es-noi18n-mapsid
-                      entity: sqlfull
-                      profile: prod
-                      war: 0
-                      protractor: 1
-                    - app-type: react-maven-h2mem-memcached
-                      entity: sql
-                      profile: dev,webpack
-                      war: 0 # TODO: need change to 1, when maven+war is fixed
-                      protractor: 1
-                    - app-type: react-maven-cassandra-session-redis
-                      entity: cassandra
-                      profile: prod
-                      war: 0
-                      protractor: 1
-                    - app-type: react-maven-couchbase-caffeine
-                      entity: couchbase
-                      profile: prod
-                      war: 0
-                      protractor: 0
-                    - app-type: react-gradle-psql-es-noi18n-mapsid
-                      entity: sqlfull
-                      profile: prod
-                      war: 0
-                      protractor: 1
-                    - app-type: react-gradle-h2mem-memcached
-                      entity: sql
-                      profile: dev,webpack
-                      war: 1
-                      protractor: 1
-                    - app-type: react-gradle-cassandra-session-redis
-                      entity: cassandra
-                      profile: prod
-                      war: 0
-                      protractor: 1
-                    - app-type: react-gradle-couchbase-caffeine
-                      entity: couchbase
-                      profile: prod
-                      war: 0
-                      protractor: 1
+  applications:
+    name: ${{ matrix.app-type }}
+    runs-on: ${{ matrix.os }}
+    defaults:
+      run:
+        working-directory: ${{ github.workspace }}/app
+    if: >-
+      !contains(github.event.head_commit.message, '[angular]') &&
+      !contains(github.event.head_commit.message, '[vue]') &&
+      !contains(github.event.pull_request.title, '[angular]') &&
+      !contains(github.event.pull_request.title, '[vue]') &&
+      !contains(github.event.head_commit.message, '[ci skip]') &&
+      !contains(github.event.head_commit.message, '[skip ci]') &&
+      !contains(github.event.pull_request.title, '[skip ci]') &&
+      !contains(github.event.pull_request.title, '[ci skip]') &&
+      github.event.action != 'closed' &&
+      (github.event.pull_request.draft == false || !contains(github.event.pull_request.labels.*.name, 'pr: skip-ci'))
+    timeout-minutes: 40
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-20.04]
+        cache: [react]
+        app-type:
+          - react-default
+        #          - react-maven-mysql-es-noi18n-mapsid
+        #          - react-maven-h2mem-memcached
+        #          - react-maven-cassandra-session-redis
+        #          # - react-maven-couchbase-caffeine
+        #          - react-gradle-mysql-es-noi18n-mapsid
+        #          - react-gradle-h2mem-memcached
+        #          - react-gradle-cassandra-session-redis
+        #          # - react-gradle-couchbase-caffeine
+        include:
+          - app-type: react-default
+            entity: sql
+            environment: prod
+            war: 0
+            e2e: 1
+            testcontainers: 0
+    #          - app-type: react-maven-mysql-es-noi18n-mapsid
+    #            entity: sqlfull
+    #            environment: prod
+    #            war: 0
+    #            e2e: 1
+    #            testcontainers: 1
+    #          - app-type: react-maven-h2mem-memcached
+    #            entity: sql
+    #            environment: prod
+    #            war: 0 # TODO: need change to 1, when maven+war is fixed
+    #            e2e: 1
+    #            testcontainers: 0
+    #          - app-type: react-maven-cassandra-session-redis
+    #            entity: cassandra
+    #            environment: prod
+    #            war: 0
+    #            e2e: 1
+    #            testcontainers: 1
+    #          # - app-type: react-maven-couchbase-caffeine
+    #          #   entity: couchbase
+    #          #   environment: prod
+    #          #   war: 0
+    #          #   e2e: 0
+    #          #   testcontainers: 0
+    #          - app-type: react-gradle-mysql-es-noi18n-mapsid
+    #            entity: sqlfull
+    #            environment: prod
+    #            war: 0
+    #            e2e: 1
+    #            testcontainers: 0
+    #          - app-type: react-gradle-h2mem-memcached
+    #            entity: sql
+    #            environment: prod
+    #            war: 1
+    #            e2e: 1
+    #            testcontainers: 0
+    #          - app-type: react-gradle-cassandra-session-redis
+    #            entity: cassandra
+    #            environment: prod
+    #            war: 0
+    #            e2e: 1
+    #            testcontainers: 1
+    #          # - app-type: react-gradle-couchbase-caffeine
+    #          #   entity: couchbase
+    #          #   environment: prod
+    #          #   war: 0
+    #          #   e2e: 1
+    #          #   testcontainers: 0
+    steps:
+      #----------------------------------------------------------------------
+      # Install all tools and check configuration
+      #----------------------------------------------------------------------
+      - name: 'SETUP: Checkout generator-jhipster'
+        uses: actions/checkout@v2
+        with:
+          path: generator-jhipster-react-mobx
+          fetch-depth: 2
+      - name: 'SETUP: environment'
+        id: setup
+        uses: ./generator-jhipster-react-mobx/.github/actions/setup
+        with:
+          entities-sample: ${{ matrix.entity }}
+          application-sample: ${{ matrix.app-type }}
+          application-environment: ${{ matrix.environment }}
+          application-packaging: ${{ (matrix.war == 1 && 'war') || 'jar' }}
+          enable-testcontainers: ${{ matrix.testcontainers == 1 }}
+      - uses: actions/setup-node@v2.1.5
+        with:
+          node-version: ${{ steps.setup.outputs.node-version }}
+      - uses: actions/setup-java@v2
+        with:
+          distribution: 'adopt'
+          java-version: ${{ steps.setup.outputs.java-version }}
+      - name: 'SETUP: load npm cache'
+        uses: actions/cache@v2.1.6
+        with:
+          path: |
+            ~/.npm
+            ~/.cache/Cypress/
+          key: ${{ runner.os }}-node-${{ steps.setup.outputs.date }}-${{ matrix.cache }}-${{ hashFiles('generator-jhipster-react-mobx/package-lock.json', 'generator-jhipster-react-mobx/**/package.json') }}
+          restore-keys: |
+            ${{ runner.os }}-node-${{ steps.setup.outputs.date }}-${{ matrix.cache }}-
+            ${{ runner.os }}-node-${{ steps.setup.outputs.date }}-
+            ${{ runner.os }}-node-${{ steps.setup.outputs.date }}
+      - name: 'SETUP: load maven cache'
+        uses: actions/cache@v2.1.6
+        with:
+          path: ~/.m2/repository
+          key: ${{ runner.os }}-maven-${{ steps.setup.outputs.date }}-${{ hashFiles('generator-jhipster-react-mobx/**/pom.xml.ejs') }}
+          restore-keys: |
+            ${{ runner.os }}-maven-${{ steps.setup.outputs.date }}-
+            ${{ runner.os }}-maven-${{ steps.setup.outputs.date }}
+      - name: 'SETUP: load gradle cache'
+        if: contains(matrix.app-type, 'gradle')
+        uses: actions/cache@v2.1.6
+        with:
+          path: |
+            ~/.gradle/caches
+            ~/.gradle/wrapper
+          key: ${{ runner.os }}-gradle-${{ steps.setup.outputs.date }}-${{ hashFiles('generator-jhipster-react-mobx/**/build.gradle.ejs') }}
+          restore-keys: |
+            ${{ runner.os }}-gradle-${{ steps.setup.outputs.date }}-
+            ${{ runner.os }}-gradle-${{ steps.setup.outputs.date }}
+      - name: 'TOOLS: configure tools installed by the system'
+        run: $JHI_SCRIPTS/03-system.sh
+      - name: 'TOOLS: configure git'
+        run: $JHI_SCRIPTS/04-git-config.sh
+      #----------------------------------------------------------------------
+      # Install JHipster and generate project+entities
+      #----------------------------------------------------------------------
+      - name: 'GENERATION: install JHipster'
+        run: $JHI_SCRIPTS/10-install-jhipster.sh
+      - name: 'GENERATION: config'
+        run: $JHI_SCRIPTS/11-generate-config.sh
+      - name: 'GENERATION: project'
+        run: $JHI_SCRIPTS/12-generate-project.sh
+      - name: 'GENERATION: replace version in generated project'
+        run: $JHI_SCRIPTS/13-replace-version-generated-project.sh
+      - name: 'GENERATION: jhipster info'
+        run: $JHI_SCRIPTS/14-jhipster-info.sh
+      #----------------------------------------------------------------------
+      # Detect changes against base commit
+      #----------------------------------------------------------------------
+      - name: 'GENERATION: Create required structure'
+        run: |
+          mkdir -p base/generator-jhipster-react-mobx
+          mkdir -p base/app
+        working-directory: ${{ github.workspace }}
+      - name: 'MERGE: Install base generator-jhipster-react-mobx'
+        continue-on-error: true
+        id: base-checkout
+        if: github.event.pull_request
+        working-directory: ${{ github.workspace }}/base/generator-jhipster-react-mobx
+        run: |
+          git clone ${{ github.workspace }}/generator-jhipster-react-mobx .
+          git checkout @~1
+          git log
+          npm uninstall -g generator-jhipster-react-mobx
+          npm install
+          npm install -g .
+      - name: 'MERGE: merge base project'
+        continue-on-error: true
+        id: base-app
+        if: steps.base-checkout.outcome == 'success'
+        working-directory: ${{ github.workspace }}/base/app
+        run: |
+          $JHI_SCRIPTS/11-generate-config.sh
+          $JHI_SCRIPTS/12-generate-project.sh --skip-install --skip-git
         env:
-            JHI_ENTITY: ${{ matrix.entity }}
-            JHI_APP: ${{ matrix.app-type }}
-            JHI_PROFILE: ${{ matrix.profile }}
-            JHI_WAR: ${{ matrix.war }}
-            JHI_PROTRACTOR: ${{ matrix.protractor }}
-        steps:
-            #----------------------------------------------------------------------
-            # Install all tools and check configuration
-            #----------------------------------------------------------------------
-            - uses: actions/checkout@v2
-            - uses: actions/setup-node@v1
-              with:
-                  node-version: ${{ matrix.node_version }}
-            - uses: actions/setup-java@v1
-              with:
-                  java-version: '11.x'
-            - name: Download latest chrome binary
-              run: |
-                  sudo apt update
-                  sudo apt install google-chrome-stable
-            - name: 'TOOLS: configure tools installed by the system'
-              run: $JHI_SCRIPTS/03-system.sh
-            - name: 'TOOLS: configure git'
-              run: $JHI_SCRIPTS/04-git-config.sh
-            #----------------------------------------------------------------------
-            # Install JHipster and generate project+entities
-            #----------------------------------------------------------------------
-            - name: 'GENERATION: install JHipster'
-              run: $JHI_SCRIPTS/10-install-jhipster.sh
-            - name: 'GENERATION: entities'
-              run: $JHI_SCRIPTS/11-generate-entities.sh
-            - name: 'GENERATION: project'
-              run: $JHI_SCRIPTS/12-generate-project.sh
-            - name: 'GENERATION: replace version in generated project'
-              run: $JHI_SCRIPTS/13-replace-version-generated-project.sh
-            - name: 'GENERATION: jhipster info'
-              run: $JHI_SCRIPTS/14-jhipster-info.sh
-            #----------------------------------------------------------------------
-            # Launch tests
-            #----------------------------------------------------------------------
-            - name: 'TESTS: frontend'
-              run: $JHI_SCRIPTS/22-tests-frontend.sh
-            - name: 'TESTS: Start docker-compose containers'
-              run: $JHI_SCRIPTS/20-docker-compose.sh
-            - name: 'TESTS: backend'
-              run: $JHI_SCRIPTS/21-tests-backend.sh
-            - name: 'TESTS: packaging'
-              run: $JHI_SCRIPTS/23-package.sh
-            - name: 'TESTS: End-to-End'
-              run: $JHI_SCRIPTS/24-tests-e2e.sh
-            - name: 'TESTS: Sonar analysis'
-              run: $JHI_SCRIPTS/25-sonar-analyze.sh
-              env:
-                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          JHI_FOLDER_APP: ${{ github.workspace }}/base/app
+      - name: 'MERGE: merge project diff'
+        continue-on-error: true
+        id: merge-is-equal
+        if: steps.base-app.outcome == 'success'
+        working-directory: ${{ github.workspace }}/base/app
+        run: |
+          # Copy git repository (clone without the files)
+          cp -a ${{ github.workspace }}/app/.git .
+          git log
+          # File keystore.p12 always changes
+          # File package-lock.json is not generated
+          # Verify if the generated source has changed
+          git add .
+          git -c color.ui=always diff -R --cached -- '.yo-rc.json' '.jhipster/**'
+          git -c color.ui=always diff -R --cached --exit-code -- . ':!.yo-rc.json' ':!.jhipster/**' ':!package-lock.json' ':!src/main/resources/config/tls/keystore.p12' || echo "::set-output name=has-changes::true"
+      - name: 'MERGE: tests should be skipped'
+        id: tests-should-be-skipped
+        if: >
+          steps.merge-is-equal.outcome == 'success' &&
+          steps.merge-is-equal.outputs.has-changes != 'true'
+        run: echo 'Skipping tests' && echo "::set-output name=skip-tests::true"
+      #----------------------------------------------------------------------
+      # Launch tests
+      #----------------------------------------------------------------------
+      - name: 'TESTS: Start docker-compose containers for e2e and backend tests'
+        if: steps.tests-should-be-skipped.outputs.skip-tests != 'true' && matrix.testcontainers != 1
+        run: npm run ci:e2e:prepare
+      #      - name: 'TESTS: backend'
+      #        id: backend
+      #        if: steps.tests-should-be-skipped.outputs.skip-tests != 'true'
+      #        run: npm run ci:backend:test
+      #      - name: 'TESTS: frontend'
+      #        if: steps.tests-should-be-skipped.outputs.skip-tests != 'true'
+      #        run: npm run ci:frontend:test
+      - name: 'TESTS: packaging'
+        if: steps.tests-should-be-skipped.outputs.skip-tests != 'true'
+        run: npm run ci:e2e:package
+      - name: 'TESTS: Start docker-compose containers for e2e tests'
+        if: steps.tests-should-be-skipped.outputs.skip-tests != 'true' && matrix.testcontainers == 1
+        run: npm run ci:e2e:prepare
+      - name: 'E2E: Run'
+        id: e2e
+        if: steps.tests-should-be-skipped.outputs.skip-tests != 'true'
+        run: npm run ci:e2e:run --if-present
+      - name: 'E2E: Teardown'
+        if: always() && matrix.e2e == 1 && steps.tests-should-be-skipped.outputs.skip-tests != 'true'
+        run: npm run ci:e2e:teardown
+      #      - name: 'BACKEND: Store failure logs'
+      #        uses: actions/upload-artifact@v2
+      #        if: always() && steps.backend.outcome == 'failure'
+      #        with:
+      #          name: log-${{ matrix.app-type }}
+      #          path: ${{ steps.setup.outputs.application-path }}/*/test-results/**/*.xml
+      - name: 'E2E: Store failure screenshots'
+        uses: actions/upload-artifact@v2
+        if: always() && steps.e2e.outcome == 'failure'
+        with:
+          name: screenshots-${{ matrix.app-type }}
+          path: ${{ steps.setup.outputs.application-path }}/*/cypress/screenshots
+#      - name: 'ANALYSIS: Sonar analysis'
+#        if: steps.tests-should-be-skipped.outputs.skip-tests != 'true'
+#        run: $JHI_SCRIPTS/25-sonar-analyze.sh
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
